module.exports = () => {
  return {
    'font-family ': '"PingFangSC","Hiragino Sans GB","Microsoft Yahei-Bold","Microsoft Yahei"',
    'text-color': '#2c2e31',
    'primary-color': '#1890FF',
    'border-radius-base': '3px',
    'font-size-base': '13px',
    'btn-height-base': '32px',
    'btn-padding-base': '0 24px',
    'btn-primary-bg': '#1890FF',
    'btn-danger-bg': '#FFF',
    'layout-body-background': '#f8f8f9',
    'layout-header-background': '#f8f8f9',
    'layout-header-height': '72px',
    'layout-header-padding': '0 0 0 0',
    'card-padding-wider': '24px',
    'tabs-title-font-size': '16px',
    'tabs-horizontal-padding': '6px 0',
    'tabs-horizontal-margin': '0 24px 0 0',
    'tabs-bar-margin': '0 0 0 0',
    'tabs-vertical-margin': '0 0 0 0',
    'label-color': '#2C2E31',
    'input-border-color': '#E6E6E7',
    'form-item-margin-bottom': '16px',
    'ant-form-item-with-help': '6.5px',
    'table-header-bg': '#f8f8fa',
    'ThemePrimary': '#1890FF',
    'Purple': '#722ED1',
    'Pink': '#EB2F96',
    'Red': '#F5222D',
    'Orange': '#FA8C16',
    'Yellow': '#FAAD14',
    'Green': '#52C41A',
    'White': '#FFFFFF',
    'Gray1': '#FAFAFA',
    'Gray2': '#F5F5F5',
    'Gray3': '#E8E8E8',
    'Gray4': '#D9D9D9',
    'Gray5': '#BFBFBF',
    'Gray7': '#8C8C8C',

    'Gray8': '#595959',
    'Gray9': '#262626',

    'ThemePrimarylight1': '#EFF7FF',
    'ThemePrimarylight2': '#D1E9FF',
    'ThemePrimarylight3': '#B5DBFF'
  };
};